# https://medium.com/axon-technologies/installing-a-windows-virtual-machine-in-a-linux-docker-container-c78e4c3f9ba1
# This article was a starting point, updated to Ubuntu 20.04 and added several enhancements and modifications

# docker network create --subnet=10.1.1.0/24 vulhubnet
#
# Add these entries to your /etc/hosts file:
#
# Vulhub lab
#10.1.1.16        win10
version: '2.2'
services:

 win10:
   build: ./win10
   container_name: win10
   hostname: win10
   stdin_open: true
   tty: true
   privileged: true
   cap_add:
     - NET_ADMIN
     - SYS_ADMIN
   volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:rw
   devices:
     - /dev/kvm
     - /dev/net/tun
   networks:
     vulhubnet:
       ipv4_address: 10.1.1.16

networks:
  vulhubnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1
